### ISSUE TITLE
Rework Sending Email Lesson Plan

### ISSUE THREAD

**Issue by jmejia** [turingschool/backend-curriculum-site#516]
Seems a little out of date but should mostly be OK. Wonder if recording a video where we use external documentation might be even better. 

http://guides.rubyonrails.org/action_mailer_basics.html

https://devcenter.heroku.com/articles/sendgrid

**Comment by mikedao** [comment]
Reworked the lesson to be much more heavier on following what we find in the documentation. 

Lesson now works with Rails 5.2.0 and Ruby 4.2.1.

I wrote the lesson plan in an order that has us mimicking the process that we used in the Consuming an API class - where we started with the view. I don't know if that's better than following the direction that the documentation goes, but we'll find out!

You can find the lesson plan here: [Sending Email v2](https://github.com/turingschool/backend-curriculum-site/blob/gh-pages/module3/lessons/sending_email_v2.md)
