### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rcm32000** [turingschool/backend-curriculum-site#524]
Model Tests
Before we dive into the deep and start changing things, let's ("great") a test to help drive our development and keep ("up") focused. Within spec/models touch article_spec.rb

I think that should be...
Model Tests
Before we dive into the deep and start changing things, let's create a test to help drive our development and keep us focused. Within spec/models touch article_spec.rb

**Comment by iandouglas** [comment]
This is helpful, but which lesson is this for?

**Comment by rcm32000** [comment]
https://github.com/turingschool/backend-curriculum-site/blob/gh-pages/module2/misc/blogger_iteration_0.md
