### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by rcm32000** [turingschool/backend-curriculum-site#525]
Rails Routing
When a Rails server gets a request from a web browser it first goes to the router. The router decides what the request is trying to do, what resources it is trying to interact with. The router dissects a request based on the address it is requesting and other HTTP parameters (like the request type of GET or PUT). Let's open the router's configuration file, config/routes.rb.

Rails used to fill this file with TONS of comments, but they take it easier on us now with just one. Let's still get rid of it and make our whole file look like this:

```ruby
Rails::Application.routes.draw do
  resources :articles
end
```

Correct code comes up automatically:
```ruby
Rails.application.routes.draw do
  resources :articles
end
```

**Comment by iandouglas** [comment]
Already fixed
