### ISSUE TITLE
Classes/Instances lesson plan - change refrig to easier to spell word

### ISSUE THREAD

**Issue by laurenfazah** [turingschool/backend-curriculum-site#63]

**Comment by s-espinosa** [comment]
@laurenfazah @bethsebian `ice_box`? `freezer`? This is an amazing issue.

**Comment by bethsebian** [comment]
@s-espinosa Yeah, I've taught this 3-4 times now and each time I curse myself for having to spell Refrigerator over and over again. Also, temperature and celsius are annoying to spell
